baseURL = "/"
languageCode = "en-us"
title = "contem."
theme = "contemplate-hugo"

# hugo
paginate = 5
#paginatePath = "/"

# custom
[params]
	tabTitle = "comtem.plate"
	enableRuleLine = true
	enableFooter = true
	titleHalf = "plate"
	logo = "ğŸ½ï¸"
	mySite="https://www.abhishekarya.com"

